name = "primitive_composition_square_content"
version = "0.1.0"
defaultTargets = ["PrimitiveCompositionSquareContent"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.34.0"

[[lean_lib]]
name = "PrimitiveTripleFilter"

[[lean_lib]]
name = "PrimitiveCompositionSquareContent"
